# Generated by Django 6.0.4 on 2026-05-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopledger',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='shopledger',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='admin_dashboard.shop'),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='admin_dashboard.product'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingcost',
            unique_together={('delivery_hub', 'min_distance_km', 'max_distance_km')},
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['hub', 'shop_type'], name='admin_dashb_hub_id_3eaa77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('name', 'hub')},
        ),
        migrations.AddIndex(
            model_name='shopledger',
            index=models.Index(fields=['shop', 'created_at'], name='admin_dashb_shop_id_651150_idx'),
        ),
        migrations.AddIndex(
            model_name='shopledger',
            index=models.Index(fields=['hub', 'created_at'], name='admin_dashb_hub_id_82f473_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopledger',
            unique_together={('inventory', 'shop')},
        ),
    ]
