# Generated by Django 5.2.3 on 2026-02-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceablePincode',
        ),
    ]
