# Generated by Django 5.2.3 on 2026-02-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_delete_serviceablepincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcost',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform earnings from this delivery', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingcost',
            name='rider_earning',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount the rider earns', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingcost',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Fee charged to the customer', max_digits=10),
        ),
    ]
