# Generated by Django 6.0.4 on 2026-05-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_initial'),
        ('inventory', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopledger',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shopledger',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='shop.order'),
        ),
        migrations.AlterUniqueTogether(
            name='shopledger',
            unique_together={('order', 'inventory', 'shop')},
        ),
    ]
