# Generated by Django 5.2.3 on 2026-03-11 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_shippingcost_platform_fee_shippingcost_rider_earning_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryhub',
            options={'verbose_name': 'Delivery Hub', 'verbose_name_plural': 'Delivery Hubs'},
        ),
        migrations.AddField(
            model_name='deliveryhub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryhub',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryhub',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='deliveryhub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliveryhub',
            name='max_delivery_radius_km',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddIndex(
            model_name='deliveryhub',
            index=models.Index(fields=['latitude', 'longitude'], name='admin_dashb_latitud_c65c1f_idx'),
        ),
    ]
