# Generated by Django 6.0.4 on 2026-05-07 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_remove_product_size_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('ml', 'Millilitre'), ('ltr', 'Litre'), ('g', 'Gram'), ('kg', 'Kilogram'), ('pcs', 'Pieces'), ('pack', 'Pack')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='admin_dashboard.product')),
            ],
        ),
    ]
