# Generated by Django 5.2.3 on 2026-03-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_product_min_stock_level_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('RESTOCK', 'Stock Added'), ('SALE', 'Order Delivered'), ('WASTAGE', 'Damaged/Expired'), ('RETURN', 'Customer Returned')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='admin_dashboard.product')),
            ],
        ),
    ]
