# Generated by Django 6.0.4 on 2026-05-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_remove_product_unit_productvariant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'unit', 'quantity')},
        ),
    ]
