# Generated by Django 5.2.3 on 2026-03-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_stocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_available',
            field=models.IntegerField(default=0),
        ),
    ]
