# Generated by Django 5.2.3 on 2026-04-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_product_stock_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='What we pay the shopkeeper', max_digits=8),
        ),
    ]
