# Generated by Django 6.0.4 on 2026-05-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhub',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryhub',
            name='mandal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryhub',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryhub',
            name='village',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='deliveryhub',
            unique_together={('name', 'state', 'district', 'mandal', 'village')},
        ),
        migrations.AddIndex(
            model_name='deliveryhub',
            index=models.Index(fields=['state', 'district'], name='admin_dashb_state_51ac05_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryhub',
            index=models.Index(fields=['district', 'mandal'], name='admin_dashb_distric_6f363a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryhub',
            index=models.Index(fields=['village'], name='admin_dashb_village_1287be_idx'),
        ),
    ]
