# Generated by Django 5.2.3 on 2026-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcost',
            name='max_distance_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shippingcost',
            name='min_distance_km',
            field=models.FloatField(),
        ),
    ]
