# Generated by Django 6.0.4 on 2026-05-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_deliveryhub_district_deliveryhub_mandal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryhub',
            options={'ordering': ['state', 'district', 'mandal', 'village'], 'verbose_name': 'Delivery Hub', 'verbose_name_plural': 'Delivery Hubs'},
        ),
        migrations.AlterField(
            model_name='deliveryhub',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryhub',
            name='mandal',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryhub',
            name='state',
            field=models.CharField(db_index=True, default='Andhra Pradesh', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryhub',
            name='village',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
