# Generated by Django 6.0.4 on 2026-06-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_deliveryhub_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('village', models.CharField(max_length=150)),
                ('business_name', models.CharField(max_length=150)),
                ('business_type', models.CharField(choices=[('HOME_MADE', 'Home Made Products'), ('CRAFTS', 'Handicrafts'), ('FOOD', 'Food Business'), ('KIRANA', 'Retail Shop'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_applications', to='admin_dashboard.deliveryhub')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='seller_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='admin_dashboard.sellerapplication'),
        ),
    ]
