# Generated by Django 6.0.4 on 2026-06-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0013_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('eyebrow', models.CharField(blank=True, help_text="e.g. '🌿 Fresh today'", max_length=60)),
                ('offer_label', models.CharField(blank=True, help_text="e.g. '20% OFF' — leave blank to hide", max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('cta_text', models.CharField(blank=True, default='Shop now', max_length=40)),
                ('cta_url', models.CharField(blank=True, default='/shop/', max_length=200)),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('shop', 'Shop / Dashboard'), ('category', 'Category Page'), ('all', 'All Pages')], default='shop', max_length=20)),
                ('banner_type', models.CharField(choices=[('promo', 'Promo / Offer'), ('announcement', 'Announcement'), ('seasonal', 'Seasonal Greeting'), ('app', 'App Download Nudge')], default='promo', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, help_text='Leave blank to show immediately', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank to show indefinitely', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
