# Generated by Django 6.0.4 on 2026-06-23 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0014_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show to ALL hubs (global banner)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='admin_dashboard.deliveryhub'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='banner',
            name='offer_label',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
