# Generated by Django 6.0.4 on 2026-06-23 04:10

import admin_dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0015_banner_hub_alter_banner_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='click_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='impression_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='banner',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a global banner shown to all hubs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='admin_dashboard.deliveryhub'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 800×300px, under 2MB', null=True, upload_to='banners/', validators=[admin_dashboard.models.validate_banner_image]),
        ),
    ]
