# Generated by Django 6.0.4 on 2026-06-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0016_banner_click_count_banner_impression_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='shop',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Marketplace commission percentage for this shop.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='True if owned by GramaCart (Dark Store/Warehouse).'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['hub', 'is_active'], name='admin_dashb_hub_id_e6caa9_idx'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__gte', 0)), name='shop_commission_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__lte', 100)), name='shop_commission_lte_hundred'),
        ),
    ]
