# Generated by Django 6.0.4 on 2026-07-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_alter_shop_options_shop_commission_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_open', models.BooleanField(default=True, help_text='Disable to stop accepting new orders.')),
                ('free_delivery_enabled', models.BooleanField(default=True)),
                ('free_delivery_min_order', models.DecimalField(decimal_places=2, default=999, help_text='Orders above this subtotal receive free delivery.', max_digits=10)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace Settings',
                'verbose_name_plural': 'Marketplace Settings',
            },
        ),
    ]
