# Generated by Django 6.0.4 on 2026-05-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('min_stock_level', models.PositiveIntegerField(default=5)),
                ('max_order_quantity', models.PositiveIntegerField(default=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='admin_dashboard.shop')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('RESTOCK', 'Stock Added'), ('SALE', 'Order Delivered'), ('WASTAGE', 'Damaged/Expired'), ('RETURN', 'Customer Returned')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventory')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['shop'], name='inventory_i_shop_id_6f5d94_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product'], name='inventory_i_product_f4f8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['shop', 'product'], name='inventory_i_shop_id_03a59f_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', models.F('cost_price'))), name='selling_price_gte_cost_price'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'shop')},
        ),
    ]
