# Generated by Django 6.0.4 on 2026-05-08 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_productvariant_unique_together'),
        ('inventory', '0001_initial'),
    ]

    operations = [

        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_product_f4f8f8_idx',
        ),

        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_shop_id_03a59f_idx',
        ),

        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inventory_items',
                to='admin_dashboard.productvariant'
            ),
            preserve_default=False,
        ),

        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('variant', 'shop')},
        ),

        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(
                fields=['variant'],
                name='inventory_i_variant_3983b1_idx'
            ),
        ),

        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(
                fields=['shop', 'variant'],
                name='inventory_i_shop_id_1e48c6_idx'
            ),
        ),

        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
    ]
