# Generated by Django 6.0.4 on 2026-05-08 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_inventory_i_product_f4f8f8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventory'),
            preserve_default=False,
        ),
    ]
