# Generated by Django 6.0.4 on 2026-05-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_productvariant_unique_together'),
        ('inventory', '0003_alter_stocklog_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='stock_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='selling_price_gte_cost_price',
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='reason',
            field=models.CharField(choices=[('RESTOCK', 'Stock Added'), ('SALE', 'Customer Order'), ('RETURN', 'Reusable Return'), ('DAMAGED_RETURN', 'Damaged Return'), ('WASTAGE', 'Broken/Damaged'), ('EXPIRED', 'Expired Product'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['reason'], name='inventory_s_reason_bde3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['created_at'], name='inventory_s_created_77ed5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='inventory_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', models.F('cost_price'))), name='inventory_selling_gte_cost'),
        ),
    ]
