# Generated by Django 6.0.4 on 2026-07-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stocklog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
