# Generated by Django 6.0.4 on 2026-07-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0018_marketplacesettings'),
        ('inventory', '0005_inventory_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='offer_label',
            field=models.CharField(blank=True, choices=[('', 'No Label'), ('BESTSELLER', 'Best Seller'), ('NEW', 'New'), ('TODAY', "Today's Deal"), ('LIMITED', 'Limited Stock'), ('POPULAR', 'Popular')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('mrp__gte', models.F('selling_price'))), name='inventory_mrp_gte_selling'),
        ),
    ]
