# Generated by Django 6.0.4 on 2026-07-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_offer_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='offer_label',
            field=models.CharField(blank=True, choices=[('', 'select offer Label'), ('BESTSELLER', 'Best Seller'), ('NEW', 'New'), ('TODAY', "Today's Deal"), ('LIMITED', 'Limited Stock'), ('POPULAR', 'Popular')], default='', max_length=20),
        ),
    ]
