# Generated by Django 6.0.4 on 2026-05-09 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0007_alter_productvariant_unique_together'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('last_duty_toggle', models.DateTimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('cycle', 'Cycle'), ('auto', 'Auto/Van')], default='bike', max_length=10)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='admin_dashboard.deliveryhub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Order Placed'), ('packed', 'Packed'), ('assigned', 'Assigned'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/%Y/%m/')),
                ('tracking_notes', models.TextField(blank=True, help_text='Rider notes about village drop-off.', null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rider_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('cod_collected', models.BooleanField(default=False)),
                ('cod_submitted', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_boy', models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'DeliveryBoy')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('nearest_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard.deliveryhub')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='shop.order')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'delivery_boy'], name='delivery_po_status_a03f6f_idx'), models.Index(fields=['created_at'], name='delivery_po_created_ec1602_idx')],
            },
        ),
    ]
