# Generated by Django 5.2.3 on 2026-03-13 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_deliveryhub_options_deliveryhub_created_at_and_more'),
        ('delivery_portal', '0002_deliveryprofile_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='tracking_notes',
            field=models.TextField(blank=True, help_text='Rider notes about village drop-off.', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='admin_dashboard.deliveryhub'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
