# Generated by Django 5.2.3 on 2026-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_portal', '0003_alter_delivery_tracking_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='last_duty_toggle',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
