# Generated by Django 6.0.4 on 2026-05-15 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_deliveryhub_options_alter_deliveryhub_district_and_more'),
        ('shop', '0003_alter_cartitem_unique_together_cartitem_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='nearest_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard.deliveryhub'),
        ),
    ]
