# Generated by Django 6.0.4 on 2026-05-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_address_is_remote_address_nearest_hub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='nearest_hub',
            new_name='delivery_hub',
        ),
    ]
