# Generated by Django 5.2.3 on 2026-02-17 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_address_landmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='label',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('parents', 'Parents'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shop.customerprofile'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['latitude', 'longitude'], name='shop_addres_latitud_a41969_idx'),
        ),
    ]
