# Generated by Django 6.0.4 on 2026-05-16 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_nearest_hub_address_delivery_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='delivery_hub',
        ),
    ]
