# Generated by Django 6.0.4 on 2026-05-16 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_address_delivery_hub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit mobile number.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(default=521150, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter valid 6 digit pincode.', regex='^\\d{6}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=100),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['customer', 'is_active'], name='shop_addres_custome_5420a5_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='shop_addres_city_7d3c38_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['pincode'], name='shop_addres_pincode_aac991_idx'),
        ),
    ]
