# Generated by Django 6.0.4 on 2026-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_address_options_remove_address_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=8, max_digits=12),
        ),
    ]
