# Generated by Django 5.2.3 on 2026-04-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_token',
            field=models.CharField(blank=True, help_text='4-digit PIN for delivery verification', max_length=4, null=True),
        ),
    ]
