# Generated by Django 6.0.4 on 2026-06-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
