# Generated by Django 6.0.4 on 2026-07-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_customerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
