# Generated by Django 6.0.4 on 2026-06-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0016_banner_click_count_banner_impression_count_and_more'),
        ('shop', '0010_order_estimated_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total customer paid for this item', max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount payable to seller', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='admin_dashboard.deliveryhub')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='shop.orderitem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='admin_dashboard.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'status'], name='settlements_shop_id_422c7b_idx'), models.Index(fields=['hub', 'status'], name='settlements_hub_id_2401b0_idx'), models.Index(fields=['created_at'], name='settlements_created_ddaea0_idx')],
            },
        ),
    ]
