# Generated by Django 6.0.4 on 2026-06-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_alter_shop_options_shop_commission_percent_and_more'),
        ('settlements', '0001_initial'),
        ('shop', '0010_order_estimated_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettlement',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, help_text='Commission percentage at settlement creation time.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shopsettlement',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, help_text='Customer paid amount for this order item.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='shopsettlement',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount payable to the shop.', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='shopsettlement',
            constraint=models.UniqueConstraint(fields=('order_item', 'shop'), name='unique_orderitem_shop_settlement'),
        ),
        migrations.AddConstraint(
            model_name='shopsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__gte', 0)), name='settlement_commission_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='shopsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__lte', 100)), name='settlement_commission_lte_hundred'),
        ),
    ]
