# Generated by Django 6.0.4 on 2026-06-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_alter_shop_options_shop_commission_percent_and_more'),
        ('settlements', '0002_alter_shopsettlement_commission_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='admin_dashboard.shop')),
            ],
            options={
                'verbose_name': 'Shop Wallet',
                'verbose_name_plural': 'Shop Wallets',
                'indexes': [models.Index(fields=['updated_at'], name='settlements_updated_5fb384_idx')],
            },
        ),
    ]
