# Generated by Django 6.0.4 on 2026-06-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_alter_shop_options_shop_commission_percent_and_more'),
        ('settlements', '0003_shopwallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='admin_dashboard.shop')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='settlements.shopwallet')),
            ],
        ),
    ]
